name: notify_pod_client
description: Starting point for a Serverpod module client.
version: 1.0.0
homepage: https://github.com/aragornz325/notify_pod
repository: https://github.com/aragornz325/notify_pod

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  serverpod_client: 2.3.0
