name: notify_pod_server
description: Starting point for a Serverpod module.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: 2.3.0
  firebase_admin: ^0.3.0

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  test: '^1.24.2'
  serverpod_test: 2.3.0

