name: notify_pod_server
description: Starting point for a Serverpod module.
version: 1.0.0
homepage: https://github.com/aragornz325/notify_pod
repository: https://github.com/aragornz325/notify_pod

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: 2.3.0
  firebase_admin: ^0.3.0
  dart_firebase_admin: ^0.4.0
  get_it: ^8.0.3
  firebase_messaging: ^11.4.3
  firebaseapis: ^0.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  logging: ^1.3.0

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  test: '^1.24.2'
  serverpod_test: 2.3.0

